### ISSUE TITLE
Change colors based on level 

### ISSUE THREAD

**Issue by RuthShryock** [ucfcs/GrowthPlus#145]
Update the background color, text color, and top bar colors based on level (see Figma) in lesson, lesson2, lesson3, lesson4, quiz, flashcard, game.

**Comment by RuthShryock** [comment]
Level 3 flashcard and quiz need to be changed to dark green instead of light green when correct answer is selected

**Comment by mackorooji8** [comment]
PR #183 would close this issue 😃
