### ISSUE TITLE
Update IntroScreen to look like Figma

### ISSUE THREAD

**Issue by RuthShryock** [ucfcs/GrowthPlus#147]
For the quizzes and games, the image (in level 1 it is the elephant)  should have a circle behind it for the quizzes and a star behind it for the game. Update according.

**Comment by leticiavrbarbosa** [comment]
check the text of the page and change the visibility.
using the circle/star fragment.

**Comment by leticiavrbarbosa** [comment]
edit xml of word image and add star/circle with togglable visibility.
alter wordImage.java
