### ISSUE TITLE
Migrate from Java to Kotlin 

### ISSUE THREAD

**Issue by RuthShryock** [ucfcs/GrowthPlus#223]
This allows for our app to be cross-platform

**Comment by JulioC-19** [comment]
@RuthShryock This is going to require a bit more planning than expected. Based on the doc, it is doable to use Kotlin multiplatform and Realm does have a Kotlin multiplatform dependency that can be used. The environment set up is different than a native android app though, we would be basically starting from scratch and need an iOS environment to be efficient with it. I'm specially curious to see how the realm dependency works with both platforms. I'll start playing around with it on the Android side cuz I don't have a Mac yet and see how things come up.
