### ISSUE TITLE
Implement timer for games

### ISSUE THREAD

**Issue by RuthShryock** [ucfcs/GrowthPlus#59]
count down from 30 to 0. Move to next question if time runs out.

**Comment by ZipZap1** [comment]
[https://stackoverflow.com/questions/32110208/creating-a-count-down-timer-java](url)
Here is how to create a timer, but I do not know where to contribute. Sorry, I am a newbie.

**Comment by JulioC-19** [comment]
@ZipZap1 Hey Friend!, thank you for looking out for us, currently, this is a senior design project for the University of Central Florida. As such, we can't have collaborators (yet). The application will be become open source after it has been released and presented to a committee of faculty at the school and we are all graduated. 

Stay tune for open source announcements in late May!
