### ISSUE TITLE
Make flashcard fragment view for equation 

### ISSUE THREAD

**Issue by RuthShryock** [ucfcs/GrowthPlus#74]
![Screenshot 2023-02-09 at 9 01 20 PM](https://user-images.githubusercontent.com/81720958/217981509-d0ebbe35-63a6-47b2-8718-0da1aae0a246.png)
create custom view for flashcard equation, we are not going to do a horizontal string but will format it as seen in the wireframe image above because we are storing the data in an easy way to read into this view. We have fields for the first number, operator, and second number.

**Comment by VictorYue** [comment]
I already made this. It's called VerticalEquation in fragments.

**Comment by RuthShryock** [comment]
Does that fragment fit within a flashcard? It should be a custom view for our flashcard, we originally made custom equation.xml but I would like like changed to a vertical view. It should be the same layout as the Vertical Equation but smaller.
